version: "3.9"
services:
  scilab-prod:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    volumes:
      - "./storage/app/experiment_files:/var/www/scilabApp/storage/app/experiment_files"
    environment:
      - APP_ENV=production
    restart: always
    ports:
      - 8000:80
      - 3000:80
