name: scilab-prod
version: "3.9"
services:
  scilab:
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    volumes:
      - experimentfiles:/var/www/scilabApp/storage/app/experiment_files
      - phpmyadmindata:/var/www/phpmyadmin
      - scilab-logs:/var/log
    environment:
      - APP_ENV=production
    ports:
      - 6480:80
      - 6443:443
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:8.0
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$DB_USERNAME --password=$$DB_PASSWORD
      interval: 5s
      retries: 10

  phpmyadmin:
    restart: unless-stopped
    image: phpmyadmin/phpmyadmin:5-fpm-alpine
    environment:
      PMA_HOST: database
      PMA_ABSOLUTE_URI: "${APP_URL}/phpmyadmin"
    volumes:
      - phpmyadmindata:/var/www/html
    depends_on:
      database:
        condition: service_healthy

volumes:
  experimentfiles:
  scilab-logs:

  mysqldata:

  phpmyadmindata:
